### ISSUE TITLE
Generator name should be 'Flow XO'

### ISSUE THREAD

**Issue by fiznool** [flowxo/flowxo-generator#4]
![screenshot from 2015-04-01 17 57 32](https://cloud.githubusercontent.com/assets/820863/6946501/99aa09ba-d898-11e4-9821-b530c2345aa8.png)

**Comment by joewoodhouse** [comment]
The name is derived from the package.json name field, taking the portion after the `generator-` bit and capitalizing it. The best we can do is change the package name from `generator-flowxo` to `generator-flowx-xo` which would produce a name of `Flow Xo` - not sure if that's better or worse (also you'd have to re-install the generator)

**Comment by fiznool** [comment]
That is incredibly dumb! I guess we should just leave it as it is.
