### ISSUE TITLE
Generator prints out `undefined` when it is done

### ISSUE THREAD

**Issue by fiznool** [flowxo/flowxo-generator#6]
![screenshot from 2015-04-01 17 59 42](https://cloud.githubusercontent.com/assets/820863/6946562/1f356d68-d899-11e4-93ea-32c97311c77d.png)

**Comment by joewoodhouse** [comment]
Fixed with https://github.com/flowxo/flowxo-generator/commit/14a6b2f9c75cc1ef9317197f6aa95f85147ccb56
